dept_text_dict = {
    'page_title': 'Dashboard',
    'Department': 'Department',
    'Employee': 'Employee',
    'Date': 'Date',
    'Choose Date': 'Choose Date',
    'All': 'All',
    'Charts': 'Charts',
    'Gantt': 'Gantt',
    'Table': 'Table',
    'Working Hours': 'Working Hours',
    'Project': 'Project',
    'Task': 'Task',
    'Hours per Project': 'Hours per Project',
    'Hours per Task': 'Hours per Task',
    'Project Category Ratio': 'Project Category Ratio',
    'All (Project Detail)': 'All (Project Detail)',
    'All (Employee Detail)': 'All (Employee Detail)',
    'Dept Type': 'Dept Type',
    'Problematic Entries': 'Problematic Entries',
    'Employees:': 'Employees:',
    'Ratio:': 'Ratio:',
    'No Description': 'No Description',
    'With Description': 'With Description',
    'Task Summary': 'Task Summary',
    'Create Task Summary': 'Create Task Summary',
    'Summary': 'Summary'
}