default_dict = {
    'page_title': 'Dashboard',
    'Select Language':'Select Language',
    'Department': 'Department',
    'Employee': 'Employee',
    'Date':'Date',
    'Choose Date': 'Choose Date',
    'All': 'All',
    'Charts': 'Charts',
    'Gantt': 'Gantt',
    'Table': 'Table',
    'Working Hours': 'Working Hours',
    'Chart':'Chart',
    'Project': 'Project',
    'Task': 'Task',
    'Hours per Project': 'Hours per Project',
    'Hours per Task': 'Hours per Task',
    'All Projects':'All Projects',
    'All Tasks':'All Tasks',
    'Choose Project':'Choose Project',
    'Project Category Ratio': 'Project Category Ratio',
    'All (Project Detail)': 'All (Project Detail)',
    'All (Employee Detail)': 'All (Employee Detail)',
    'Default':'Default',
    'Project Detail':'Project Detail',
    'Dept Type': 'Dept Type',
    'Problematic Entries': 'Problematic Entries',
    'Employees': 'Employees',
    'Ratio': 'Ratio',
    'No Description': 'No Description',
    'With Description': 'With Description',
    'Task Summary': 'Task Summary',
    'Create Task Summary': 'Create Task Summary',
    'Summary': 'Summary',
    'Ask AI':'Ask AI',
    'No timesheet data found':'No timesheet data found',
    'Invalid Date':'Invalid Date',
    'No data found.':'No data found.',
    'Ask AI':'Ask AI',
    'Switch Languages':'Switch Languages',
    'Start Date':'Start Date',
    'End Date':'End Date',
    'Task Insights':'Task Insights',
    "Table: No Description":"Table: No Description",
    "Table: With Description":"Table: With Description",
    "Task Insights":"Task Insights"
}

chinese_dict = {
    'page_title': '儀表板',
    'Department': '部門',
    'Employee': '員工',
    'Date': '日期',
    'Choose Date': '選擇日期',
    'All': '全部',
    'Charts': '圖表',
    'Gantt': '甘特圖',
    'Table': '表格',
    'Working Hours': '工作時數',
    'Chart': '圖表',
    'Project': '專案',
    'Task': '任務',
    'Hours per Project': '每個專案的時數',
    'Hours per Task': '每個任務的時數',
    'All Projects': '所有專案',
    'All Tasks': '所有任務',
    'Choose Project': '選擇專案',
    'Project Category Ratio': '專案類別比例',
    'All (Project Detail)': '所有（專案細節）',
    'All (Employee Detail)': '所有（員工細節）',
    'Default': '預設',
    'Project Detail': '專案細節',
    'Dept Type': '部門類型',
    'Problematic Entries': '問題條目',
    'Employees:': '員工：',
    'Ratio:': '比例：',
    'No Description': '無描述',
    'With Description': '有描述',
    'Task Summary': '任務摘要',
    'Create Task Summary': '創建任務摘要',
    'Summary': '摘要',
    'Ask AI':'詢問AI',
    'Switch Languages':'切換語言',
    'Start Date':'開始日期',
    'End Date':'結束日期',
    'No timesheet data found':'沒有資料',
    'Table: No Description':'表格： 無描述',
    'Table: With Description':'表格： 有描述',
    'Task Insights':'任務洞察'
}

def getdefaultDict():
    return default_dict

def getChineseDict():
    return chinese_dict